<?php return array (
  'companyName' => 'NoTime',
  'country' => 'España',
  'stateProvince' => 'Córdoba',
  'address' => 'NoTimeLand',
  'city' => 'Córdoba',
  'zipCode' => '14014',
  'email' => 'noreply@notime.es',
  'fax' => '234234234',
  'phone' => '23423423',
  'mobile' => '32432423',
  'note' => 'Thank you!',
  'term' => 'Please, pay me, I\'m begging you!',
  'display_country' => true,
  'currency_symbol' => 'drojas duras',
  'currency_code' => 'USD',
);